kind: Deployment
apiVersion: apps/v1
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    spec:
      containers:
        - name: jellyfin
          image: ghcr.io/jellyfin/jellyfin:10.9.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 3000m
              memory: 4Gi
              gpu.intel.com/i915: 1000m
          envFrom:
            - configMapRef:
                name: jellyfin-env
          ports:
            - name: http
              containerPort: 8096
          volumeMounts:
            - name: config
              mountPath: /config
            - name: nas-media
              mountPath: /nas/media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: nas-media
          nfs:
            server: 192.168.1.55
            path: /mnt/pool-0/media
