apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  volumeName: jellyfin-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
