apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  storageClassName: proxmox-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
