---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAEwSDdscHo8F72e2vHcXI3ZLB9xLfim5nDMeY8roWrW/q8OmZy1oeMIht2RdepxZjimUVraA6a8j32xTRuxFLZl0g3l829crney8Ws6pYBOFzydwWptL8AJ5bjSN8qxDELyqud6DUKRsefvujZoKToAGtG1V1BoFDycRxwc3FrWvFYyCz/rluvXg2+WhL/05dRxu42A9LX71w07Q8GR1pARTfqrrutM/4UvEvI87HM0rWZHArSuAq5n3CM7d2vDn+leRuwFtRjsuGg1PAo1xifB2uy5wiLWlYYl9Futzo8zE670SHZxD9A8PjTV2E9hKiipIOdnaKrJ99h//+QiczMd5Lo5AWxd2m4IT58/+NZSThfEh6I3FdIWISAu9d8qYrJoabmsbK6ludeOk0wGZkO3iQwbl7fgJrl/GWfnge560wCw5Wti2UTMN35O+PiG8NNnuWn5YCalpGzUARbx70vwYxrbL1+OIzzCo1l7a8m0NBCazVtF3CthvHR1r47Jnix/jA7aJuKJ1uKKVrt3z5BynRCNqWTenJaghkggJn+YfI05NlgwPwlIcd23xDb9WYr0lmt2K+MuTK4q80sCNnL6uB5iRlB33J6J8GNcA0xXXd/lh9NugPfA3fcss1xJIEkj1RylrwKVzXpuAIuTJoJGROo1z9PcrNZe0OjGsnVr5SbfwDxtDTCIQKG4WSMSttvWU87ruL+MxMqg1OLMJRDTl9TeLQnBRIDVcNymbFptInCBuSUQZICfrkmqIMpx/1fpE6s5yYtbMMuefu+FnXZ2F81Ni8SQbCD8pPKlasOAczQT6jQAWyyYa+2Tkpb0xoxUku+RjwqsLThXsuxMCELx1j/RftVrQhw4zJkomthtEssNBtWoqTVbtbHOLqKeG8Y21UdAcpAg06ctVwBBKHwAg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
