---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAETXqf34WwPPJlUk9pjYH3QgE1gF11FnboZ4FDYpI4x9F/SDKOywhLeFSZn5+gnPnV6so3do+JCgUM9ONX7U7ZayJOHdCiSrqgC4Yxi2OceEDtsAYeqDRFR5armbwBJEHdEmfF1/aIYnNUarKiBeiKqHHcK54JwL4iNxM+dfXSVN31I3UzeWzLN0sPOGiBqSR3JgNUkQnwd6xiQW4zefCn8CpkaXoXDe3jC4+ZIVZMgqneqVYEkNyzHoU8SSMepluTRNcOxI0gLuuB5mVQkKqdREJZFJdCj1XFwLNETkXC5hHv5lYI5zG8Gyj4LpGSwJWJsW7fY7YQt9LejOoeuHziv04Pk7TH9TBhELU8Ex0/QhuI/lu3sLdiUt4Wf/QrDtuufunRr8kBNKeAvx+S6ImxuhSVqPG2QOC9GgqTl2s38oRGEN6wbiJ+Bx4atZrjNtYUMpqYpObkw9KI84eeLgZufBm6qxdDOnaHy1zpGZ+32jMcUTFmixV+4h0MdUSdftTbQ99cCFgzq1cJPiEl+eIlZpCuIn2QhEkNTK8na6LD2yPcBHbd/DyzTFL857wZc8zE/OeLw8Vm12zpk0jtmpRC7MndxfOKS0rbS6N4ojmmRDFKeSipd//x/j5Y6DqB7KYLUJy1nbrKxZSFwCs09uCxukFr0l4tZX6GzA9kKOw0s/yXXcMcJk6edMIzt5uhCaXj6BqsjP+w9k8g0+as46fYBGq+Yi9sv3Mkwj8oBE3dEbZM0yNV1bN8EwTB0CsHsyZbruRLDkf41BwJ3ti0R1XJU7iqpLgMEbnQ0KuQ8Eu3HxpI1QL0n2KMFAPn/U7vOz8AHq2VO8RZRBmH0f+OEgXrelbBQXx/aB/KlnfKK0/MAuDLh6DdtzZK2eHk008GhcQ+3Qty+rQ+WUtC0Te18vDciQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
