apiVersion: v1
kind: Pod
metadata:
  name: utils
  labels:
    app: utils
spec:
  containers:
    - name: utils
      image: arunvelsriram/utils
      command:
      - "/bin/bash"
      - "-c"
      - "sleep 36000"