apiVersion: v1
kind: PersistentVolume
metadata:
  name: euclid-media
spec:
  capacity:
    storage: 512Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.42
    path: /rpool/data/media