---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgARo8IWpvWnw49/S4G3LUzlmpkwv8QO019kim7cy6RAwHB0H5CN93W6DoZtjfvhQZiXwhc6ssNHH84io/3hoDCdq5f2DbgvuT7Gi9hMCeyCpYRdH8zJkCjQxggaz1f9W5+192A5I9ICX7cbmNYMNPdtBrY3/cOF6ygp5eHF7X9Uka9T5Y3sgSm3AadmrleB9XYkkSB31m7pCxSQmTULHOEQ2LwbObyVbvDNJz4ru6ZsjZ3e8iDATaEYlo456WwrVoWF2HnaNiLaL0PAzNwsJaEgXavFLFKhIm6l204I5rE4deIpdcK6oYsIlwL5mDXPX42aEI9kLZaTd6uRNCfFccrR98f9qWSVe4hxNN9NKut2ksWvXhYVhvjN35v0uGDUn2GUC4GNUUdIUWRDjTvdR5t/rILeZjGj2RNVJgVqgjSOHhYY6G0vSa5ed5tRIAdGSdmwRt5QHxGbhV36LGMLprHtTu83cR8ZPnas1G4IT2ner2yv1Ia1DQEWxb6WibMq23tZnjDMSedz8gG0qba7OkUY1uuHCrFmR98TtcR9XCrHHLtKbZsbwFLe4ZcEs+M7F/QYGhf/8jqfV+P+K1vIYQpEEQTeEBo17hRcyaohZdYUVXV3CqUpd0Ith6Y+7LkXDZy32DYl9Z/S+alXN9ae9BM8pv6AY88wLpgew2sQ36LwoNhmYohApxRDOxfUJVkNSY1bkpZ5F4FAoLQDW97HpcWBgFaQvP8VY55ca4QRkPb6Bdud0NXbhVMC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
