apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgBefK44UCMfpix6oZDRhhA+G4SjakPm/iQhFwtA67zi3Ed1f6JeKl6I3juvaZHDOX6ojA3Nq2FekU7AOKhncXEhH8b0HVyxrwpb+BfX2YujqytiJb8NSVxKounlxUJIvgaq5BQ1Lf7vIHnNg6uI0iruXEcVo7KeiJRkABVA+npGdnFHo2yoxgGu6wRHd+/+ifV9k9Cz/B+F/i5Q47Ie7dSirCGH0cuSC8TxD2soLnH0EhrHRaE1dD4NTT1N6uXKtUxgoFDR3XAhEawZnOObmE5zSGwR/CX1OXo5v8mXJg7+i5tZ8E2jDOX16GRz+l3DH5d34V4DtXcedI2k88yVQJ8ALvKIuBinjxRmSvKxqnsIvmw+1fuX4/T4bhP4yscBuqi+gz4rgx4WCyNALxzCD1shEZEUbM/l8jtByVL05xvmijxx5f6k9xB7SbXBEpSX7gZN502fFDFcTP+wATWcyvBBkOb7wiAWn2ClB22kad8Jh2HIRkLPStc9cbXMILt9sTLlTLULPuZ4xdOL69CSmD0dfe0/1iB02vf6Ch5zokS/IL5+a07hmrOOr9SYsu12yv+lz53WtF4VbdIA/hWUJ2bq3tGdQdK2y8RMGZzt9Ffuo449rt67eF2xbTGSaWvsZazwa8m3xWH4pny7vrrQmH7rrsNClY5aUUmL8euiokFJtoI/yxriBGMIRRrYG82xCUyaaHrcOasVe3kBVT+6bso3vIZcxOxIV/7/2c19fsyBe3ACnpbDhoNy
  template:
    metadata:
      name: cloudflare-api-token
      namespace: gateway
