---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgBnmmIhddqg+EHYBEnGMEG6qTvsUjpRig0Q2ptFKqt+N09OpxXL5ka/X4hbZoYyajdguS/Aqog5by4n7QsCEYirHOfw6qzPW39edjkUJQ7uz4wftqWVLgIAOM3cPG4o3YM8n1OUgTe5Nn1ttvlyXWC/+pwVXh3IumsEPjF9VfWCKBuskmg7H6lMw/6oHp2zXT8L1D8Qj5Rni9l2syHF1FY61VFj33SkjhYywNAz4LyoVIEKZzmkf6ncDvyBpD/oPbuPt9rSSc2irtxviQ5ijmHvq01dFreJ9TsPcRqxgZmAiZKgkEdu+ZcIzjPBXoxwc5lOsYBTQTZooQHUkdkDYC6dN9mUqdojbQQTZt9V9nbyUMMh/Mb7uRD0TOL0aDkAx12CZ7Xhy/OQyV6d278lelf1rFNqNsXk+chkHO5HHBNNzYI81aCM1QNntToXBvVQ86ufcRsHtbL+SPfuYh4u8XPOKNB8zSEzSsGbdO0n1HU8uRxWNVo+zo/VtOxm9CiAOjyXBMGdIcriqs9pF78FkWdZ5nAChCFF4Eh6R2c11ET7fYJaQ7uehHujslumVYe9TMqpBnIjh/n70+TpCUVQvlgrY6jBOWO0NLuwyTWm+r0WARTIa1wax1G4ulfSSuRF1WeYtfE4wFzNQRKx0gLGOsN384ZuvbeoRH/CVai4sXh3kAxVqKv589JEIbAXJF5ycvV1kb6feXBf+gZgUbrdmiPgu8adI73FCq1EFpmLgXIqPEmmy94vyb0K
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
