---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgALEU2SQPCPNJ00XtwTbSHQiYdB3wvl///HdDVhDRq5mma33+eo7EXsi6zKPU56ma/eE1o/JC7VpJpz//awP+Fu0IM07rPmrKamBdbgxE71wdcQN1a02vTogfB9z6fqQKkC+JUnHfPZR1TVuj3/jp+1BXrI4Db0D8C6DC+jZ9wRf746q0CF+ijsyhjhsAulPVfI5UwI3CR5Zke0Xt5b4Xcz6FzhTIubTudyoRX7RCsVNBqOJY1jFkQmxZIA5bDMixXcIwHSMwWVnad1IlLIS7MfbGRZ20L/vg/n3hGopadax8TZImRGFkG5ArLr+i+GsNRlQPVCb1+8BwjvtimX7rMQQpSauMzoNh9ibrROu6LKLrp7/519D4LNQ3CgUgNuFlofI8dJiWKLQZ42CNZZ+zGDUrI0ti9+GzhBNa3A+w1jwHUoXij5zXNaTMZJ1+bWiEGawJqV+H5I0GYa8dFm30/k3cXfIHx4d8qfih7MUo0SsP+AAVpBVgE2XqhlV8FKemMFfb4a1ccirlklIT52nLLkMDtBrIiIPyjZZoLSs2CNO48mQ9q1F+14OXcF4xKz/dKXcwCr6epBJqxcoT8WdU5F2vYSHz1NXMlXhCjFuKU4RuALzz55v2qlDeZaiF1AzSml8sX631By6/BtCbsKYlkP+pUZgS5A4zRgeHsKc8L3Tq/BkcarV2fgJ9pv5LssN7vdKgyTNvnDYu23GuuUWYUS6KKRMUFePCU+6eZc/JPBOcYZcQGuACpK
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
