apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
commonLabels:
  app: plex

configMapGenerator:
  - name: plex-env
    literals:
      - PUID="1000"
      - PGID="1000"
      - UMASK="002"
      - TZ="Europe/Oslo"

resources:
  - pv-plex-config.yaml
  - pvc-plex-config.yaml
  - pv-plex-media.yaml
  - pvc-plex-media.yaml
  - svc.yaml
  - deployment.yaml
#  - ingress.yaml
  - http-route.yaml
