apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: plex

configMapGenerator:
  - name: plex-env
    literals:
      - TZ="Europe/Oslo"

resources:
#  - svc.yaml
#  - deployment.yaml
#  - ingress.yaml
  - http-route.yaml
