apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
commonLabels:
  app: plex

configMapGenerator:
  - name: plex-env
    literals:
#      - PUID="1000"
#      - PGID="1000"
#      - UMASK="002"
      - TZ="Europe/Oslo"

resources:
  - svc.yaml
  - deployment.yaml
#  - ingress.yaml
  - http-route.yaml
