apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: plex-conf
  resources:
    requests:
      storage: 8Gi
