apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: plex-media
  resources:
    requests:
      storage: 12Ti
