apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: euclid-media
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: euclid-media
  resources:
    requests:
      storage: 512Gi
