apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgAc+P6j4kNlLFZp1zh/uVZFN3uz2zKe1R4T1iuraJYHUujNpGAP9X/vJWLHzzBpboXuqiLReP8VIlcFZKNxanXjVWA7saY5t/Jgz820f7hZKfFE04USboDijFrTNLkxPsPEZrF3wOAU5j049s7ek73m42Pl9L47IG2shBmY7FVLamY59VdBZ3gjRUK+W8Tc16G79VteL6JplbhhR649JWWz59CWAL/fB8sq2QzjJkxBa7H5tiamxkGXgkKoSPBCxQ1w5/zvnD8vv957Xc+IlEpj17N1WESmiyrYdVvBJskCGcFoPlKXReeZT7petrWb6Lmapapa9LZnpSWgDzo9M0kbqBeRYr3m+v85PfUGMzlu98EEXyM2dpjqTJgKVmhqJwAxXw6R1oRauQ8fNr/JRu3ExcVgKIVAdr6rvXwLXR9OfTscTNxGTCiJ1ELirwccZvf5Q9v5CrfZu9BPjr5aYZdmIDqyTNj05HgV6+wwnK3sOACK9ww463Uomg+eel4wYvMIAzDhn36+S3vV80DEAuq6e0F4TvIrH2qPt2hZZThrYTc6tz+hSmSdddu1mhXmSyuZR4k4NHmavMakV+04WiulwkmwEWFVFI6wlCHvyajQP6/ebc6tXqPGEh6nJmfL/EL0H7/J+2WNpA8gQSkZFUlX3k0Ud/d8fwDh4u/GukloNYuBm1mPM7IUKf17OzqWT1eS5xFszZ6Z9WX6S3gdIWZpWr1SzxK59THGn0xxbJVHK5ghBKhml+2ZmhHTrUHf3sthUP6Pw4fuxyIGsFeTbaLa1Trq8xGtu3eZ7lIV8KzmyLADKW5BVENRsEKZmAQqgnxZBRaOZwicc/li3FiGEv3ADpaY9BvDBjV83/7Qg+1g4+OW/LMxYsngoEvQNcZH4c1zEHg5hkQYBWA0w9NoDj4gV8bBy/VDRvdpEcAxaA==
  template:
    metadata:
      name: proxmox-cloud-controller-manager
      namespace: kube-system
