---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgAuwnl2hq3p1BFoTHuv4bwy0pclGs35CAoJ86pz39e3wUMdcYZF8SFtK2UQ9/ZfSzLWWOxzTV+S9jGgSIRYfb6kFCPWNyIjnZmRhLGX6qhK4QUeGNg1BHP+G8S6aRrFtQ767+SRhXW4B+xb8q0cdEQTo8RMUdBoso4l6U1uhBo2XJOMDlZjnobdQ/elUnJbdPKk5diFTp7PBFbdxVgl6SGKc0lo5xchwpv5WHUt19ClX71FWGHHun91JxwV5ZuwHQKCxFKaBwLkx4smnV3cgWSm6C0SzjcLA83b+UPpUBcXkKJeXxSmMVXYYL6h5a5t1k546luKeSUm5lkPyoiAwtLAiKo4dWyizNrHyKKmjMnfXAOBMpnyxho3q9W6ffZC9X0/visfOWbQcls/qoh6CHf+w7DABsD6JwSGs5eoaCdynllC7p+dSk42yaY1fvh9PchIQcy3rZ+Pa848guyIblpNCq/UtYjAHGzSR+apocEU/Fsz1PEGgt9xxdLBgly8wbZx5tBBI13NUHs/8HJ5IC2tC0wJAd7Em7qo222OIaj2FRCc82fKNm7dk3NeXeodIyT6wli92vmbqnoCybkuFyKIwNPQ0ZL2DLhY1u4qVPljyxAS1nJttpbTvgUIfZNSg47aZ5UH1JOvoBjlcana159a3CREW8lQwUymoi5aWt1TS9ocMc8RJ9DnOviFdX879vqK6F5ctNT4B4ISO79j73ZzZcCGzrnz4NW5vMEgTG/weQjrQbJWA4dWA2HnWIQzGddF1k1lSOvF7uznHl6YUVw6Pow3bK0yugt4Dc1IxsPShCxEq42OIPXo9uNJlivXDkD/8B/7kb07kjzyw6JpX32H5amFlo9foRiRZp0STeT+GNxz0ejb7Ysqld5FXI3bvMFFj5sD/cbDWNZGPTcmnw9zg9TCLxLOy2xRcuWk/A==
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-cloud-controller-manager
      namespace: kube-system
