---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDCzVgyIOVePgk3NkpM5Grq7FY4MXVw5BUE4jinMBCmPDFWc1hT1wj0AsN4QNi2PNAptjV41srDhFSzs7QOBJJbZs/r8OacFIwAPdiBIyVKUtpSZ7ZQJJ6Xty1UiVeBKOwuEMxIdB40V0o2wkKVY4aMcJllp2mWeNnKFwR7ttjkjqEQUxKkwY1u4yR5Vuy9SyZW4fQ/I0c9DmxsR9cQ/l5Tw0H5m0j1jIEhKRpyuqcNf6kTw0w8xNOBigJ1w2rMFaBmPgPwOVQrw57JYI0Myzcsb0UOZAqR5rn0u3SrPycM3roPlLWQ8MI8wQSVggYPku2BtpCln1l3xAqCueFLfmC7fx18BP9CeXUio29qSVgLk8BPM/vwqcxr7Ti5VMSlMu0GV0YChnazO5jm6trl6ZtyeEAZQe9+AlCATXoM51Pp0aQZg0028cqz7XQmlelMYwLPRSCJKjbCwiogNTWdO3zSPQd9dPNWyve2aD8U8BV396TMnkDDchERVuwTw8tr1o4B2fWEl3sE0MXZpYNGuX8aPHHPgD+GhJYS5yTx49Etf5we7lkiqU2cfB5TfslFrZy4n0nw8v+2wEEAEY+dgXwjZINQ2VDDOHZc6+DHXJ0xoiw7L8rqHe0EAxI0RFR0QTuM2A/Tyo2C/z2Youicfnl/IUhVT4Abd1OSx7WQOvEgdrICIKP0Xd/607v97vg37EF0xgOqabmBkBXThdhzM/T7S1TN45x0JN7NLW6ulVkXvxMETnrS9BeT
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
