apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgALkt8Tabm/Arr214TCXvK0zE/g7puN9Ml0gFQuI2XfFZjkOu084DpHB0whGvqPoJbZaNhB5ATD8H6NH37FJqeMvcCWOuIj09J73XjQdGRANqaxTGOidtBKLzJJgg3NUEgKUj09CgDXri40izHkrsxE9vv0aKY20bqyT5x3xG2vMpE12yKnUW117y2uIUF/IKhhtg0uiUHUKlzBuJRHzOl9uKYs8EJUawDq5Eq7X1QLLmOdDBYrsJW5NMZJVA4rxk/yALDNmxIHfzrlLyMAp1uhYgt2d+Iv6fNcJUoEeCuBg4JYh1RcdaC0Fqj9az0vAPrGiSwS4/GBIjrM2WYBpOuICGmuh9QgBV+EmNYaB7LMkRDfquuoZmoip++1WPF9kDke/fWY9KW9SrdogZwqYDKBPyFHBafwCKL0/CveN2229QCOwy99rwd5XdEFGvAvCQytJ1RMJcIrloTDZQXx2WapbO92uHGj5BuED3nMhfpFQx8VeOLhBqN7SSQEwzxYUFAIT3bzeoqJcVSHFqVuqLW5X8vQajCU4skdRyYZymdJVSyAXj02c+4J52NdYZ/gNY52XMjHsW1cOjA26uQXWAOvHbr6GCdNZgl/5TtK9Iv/xKqJlCEJqeN55ZBp0eeEIabD7j0e6J5hrWV+AsuvVg2MXQ4ik8KSBojHVSUoMuW53gjf2RYVsreBorOtbHmt41Plbl1hOfHKoOX1sN7oLGT4Ac+JnrEdiDoYhXVFXmoZOHboYPKVrQqP
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager