---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgB0N/t+7LRIO3ShTijz+KClR8421hi0tfQWobVQh74i7x47HU7baPQyAOrUpZBphbFA/1hiZy40NRGknB87GayWYXTY5+sYkTHIapP+DAmmuLyC6mS5Ldtj2Y+vhesbLbDayfoiHCRPK7IvBe98HK7dLBQdPyIg/gamz6/TAYHY/H8KsYgtFE1RXO2bCiJ6WULOtR+ODwPNJ/8NEsAKcM3yaJys2Hnh5v0nR+nUwVsySLgNPAXyTaA0VPYD0fl72epF5JXUUbus8B/C7sgpA5BHlo9mDF8DGYabR2O+q7ydv30Q5hxprmMaBVAA31D/721yQYPvPdn8tmlbMcGqnmq+vHD88PXgCZRFRxPYESEUMDH0l9vnP2QS3cs1EPl1bvavbyk+D9xF4x0u7hUq4Mgkem/tnQkvfgcThF8yaKcpTnmGGZ8ethGk/haYMWvaO5ISdpxJuNiaX8Rfi1yrNk5PtwAFIQc8wRO21fK5KsoAY79F9i6Xmcdq08x3uEDqm3Ju9JQOrqJ0JPJ/pnNS3qmrld+q/PLwcVmZG+xTXxoO9BFnUwoKEyuDIL8P5VV/JS8950450l/mNXdw1IqvHEnfIAb712krVv5va2EWpm6REtIDNBJOtFOslY5WwvYGerSY2rRpMpq2vaoL0c64r8lcTy7V6rK7J6K+MkgmbPqi9tj4QGjuSVMN/LFsIYiT286GgGOEnbi4lNbxaY1pNFIiWOO5tUA3a/F0y0QpoPLWdcoMrQTjo4Xr/ixQ/1G/f3DftkNnTJczPiLg56lwddh0/phqVQzIeD+NdI3/irDBt1deZk8TRaZw0dAvpETVX+y1/qHoAt+C7niv2evRT42HzjQWangtSGI+FPnExVwdldvaoTVvJTspm44wnG3dZ0+jBKDhNHoPilSDXlDwqsaS19CkFHQCC4r/eQrgVueUrlRuWBA=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-plugin
      namespace: csi-proxmox
