---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCAriZc3dFPVd+RqQndx1Lq5YCNoJesy8QYxBtv6x3TaNNBDFaHzoVF79dD7XSJtBI4TQbDoEX3RcJHMekco93i6mmWEKLr+hd/Tqrid0o+iUef4OJMkhFoUcL+XoSa04CeD4Fh1IIpB9W/BrjQga/QtK98ECQJBnO93fGCV4CV4EtX9wukESa0zYQWe0gSIbwLgpL3xO3l5eRV8cSZ5dktsPJfqhWKXtVZgzXbQdTh2njhpdWluHyyqtsg4I75MgKmIPdnaL/KS6LLhY7b8q8QHKWL4n2Rl8T7sp610cEuOU2MNlM5XRwUAM8h097/GAbPu16wER5wp4Ch4enAEiecnBSL4cXPushYm8NmJmkj1VnCh7BF3t+Ax38oNC7WsrmxNaZKMBi6LbwyH+ahnPVtwDCsxaT/3OWuxrYI85ND4WSl7kWYGunG8MfnAWMrEzWTtFt0W6AWkTMfFhO5BvQlN6NcqTPKqksb9fjWWe5AfeMJxrlpOYvQ1X7avOpnxDA5m8Te2KZx5z4OgZibjeJYka01+P9TTiL9W4kG8/BoOnii6JN3DwY1FfQfYiqEOkWXiid3OFLypDkYV3eiGq2Yx05N4QyKLfbBBgCK2cjgAgal+rXix96qR51bUrNFoRIKVw+AIWOSwzvOhVtCxX30+xYGCq8JvxGtWuMFtAoV/N7KyblUGvbHcfdXiErZLazM1ATx6aKfUH1v1bwaIKqPkdQV5LVi0IOqLjb3kQ3RMgbXxqr4u2524djQQ4wJL/cwYHS+MQccnAbBqOgUx9PaqYNuhJHiLfN4FTWC92wiTUCTynmiTY32ChGJy9yG6P+YCXHKNgUcYPNHCKH+XmH8lapYRtjkHOYK4TmKcheuoGps5N1em8GdQCe/ljuWurN5jSqtYExhvLb9DOGgDj30lWg5wx6zUODxz42S5xXoHYloKi4=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-plugin
      namespace: csi-proxmox
