---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgA9AB81KwkViLunxsQZwf3BO2wjyZd8SOFbiUnekOPaX6bCvSFqliAID49lxS4jLiwJJtBrIp18AABmdFg7RH6GL54JYi2QDVw4Eg/W69NEW2d2TSKSTBD36ka0Y68nldU5S5LAEHIcLqeNvSkOE5D7v2qqiASx5uC/giurF1D8lS+sANcUgq0jeZPNk92CJgb85+RJBiFaAGHSqcmpg6LSrXaaeGY0P3AWr33w+jqngTEbdyT2w8myj+mTOWS4WwcHNpWctDT8kNuU7xe+2vMHosC7oxHch6Oc/qdnOItw/SH9DLsZ9REKy7IWU3ZCpX5XEB2kFoytQHkY9pwXe+rfncmwrvU5Hwbnp4gJ+k4Gyy4mJAXifOfJcr/+jCAZxYzYbJ9YlW+auTSg9PSnAh9RCqUHGKOYQvxZym43cOaYlGiVxYIS1ILGWT8oIPCTTms25l43pJFikRo53nPnp0GjrZE0duoxrEFVlNH8KiPDoEJKy7iGaXMkZV23NQyWNSRjc2K7tKG2EYIrMUSocAheZKkkefSsfO9519HTUMFV9raUbCgLO5KxXMG4o2jLd1Joyop1GnEojgIzAEwCSuzXeltgO7Pwsos2VLFsLl9gk1E0peJZAv/EoN/OGenASJeZxEZNDO28tWcDDB0p69aNxfbhDJQIyarOuTSywedY+hFidfauKa7TRYA3X7w0OCHpWPtw3+hym+sdKYSFGOLy9LVgRbrnvYXPFN4SLDCk0y0HgTub0AhFamLHdy6/GIJD1SuFNWY3OR24raNn8SnoNBeeJk7JbTTSqvqa97sZWGQSXmztDvtAjcoM82YBfth84HqvnSW21rDG26RcP/1/biswMkqZ7wUuzbmVkrsdtFy26dXdBSrpBI0hyB3T2rgT89epOb2tiRJY9RCMIV08a7JQWs4pyKCkA0h5VXA8lkoMVyE=
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-plugin
      namespace: csi-proxmox
