apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-zfs
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: xfs
  storage: data
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
