apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: adguard-work
  resources:
    requests:
      storage: 1Gi