apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/SaschaJohn/mini-homelab.git'
    - 'https://argoproj.github.io/argo-helm'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
