---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB8XoDYuVB4LyxLazrPmorl2fOwLv/9jTdpZNYWUQjY8dgHqC1BXRbEYkLpYWvIUDE5mjAX5GVZAYOMve/rk+4ZnLvFy76npNjT5V/SuWIW0z6m+aSy14aRYaXjSSovnOmfmAtWFQezA2xNMFaygjAuZPmMmjvX3X3n55U3fA+blCS4LuCMksNxFFl6Jdz0qBcDywAez6acgZdwKOObL/1VMxmxkjYvSNYvOMFrYQeK6aD5vdQQMI5U7gBjf+UuDSW4MlqSdv0fReJWa4ZP8rV/l+Q4Zrw8lF7eEOhJryNh+oy/fpeZ9jpNTW5/iCzIo17sMSOWrZxqiOJrulZOsebRjx9I93diAx+r9/snUQ6E4xPsz1NOBxx9JDxvfrQWbtwtJUFCqG50RBks42K/eUjYxqRZsoAN6KQi5n17waBbsBeRHBvnb5TF/7UY0YL27T0jvHLUwf5eXYIe4MgjIzk1CIBneYAZdCfHh/48+bjt8tgGCUWG+sFI0sd7FXPPnUttqN2UJyJG/wGxeX9divv5+inL6wPGftI7E0lCY5egW+bO26pV7V6nDLSyjovLJOuX86eXl2Y+2fTNrEXCsA3r5I3/o9EYzlaZfihVmoDD3h6TjqOcg0d+kmGHMXl5KVLQu3wXCEg0a+sT1vhDs/bbTk00f4hX+kSOR1jor0uBLckNt3NxtdegKhckhw72sm3HudWwNI5/d3p2xT2zCK0B3C8M1mL8dSnkzy/0YWUpxrbaDFzQA9Tr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
