---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBFoW5A8UBoL4U7Dj0IgqqpJq6LuPYOhT0wjKV55YjUPthuShmcr6U9VJG+eYFiCwAnyPj92CE6li9bJoOD/pDQKXkTDd2PE84vEWi8kHYSqkLoglYsa0dmv+2Q4RUpXSEsVqvMJV29RGqFuSrxut5vzCcpnEQlSYmcpkp4ZVyOXClo2FF0yzfmnqiEkhbCDQ1zb9++5gppkhmAO6BPv0CwEnvxb0w1gqz0KVBNkjc1RIrbhS8Weoz2ZJLzKrvuBtusWfH+LAJS8tWpYTgmgrl0c+b7ksD7HNq7AqvDdWgrBA5zOxTj4IP8cwSKR4OuK66b0RvoiP2uyi8G9eO4yVF5+f+yf+SEvf3AMHOKViZbFeq+jcQUTU4M9Zp1kuC9DJk9eHax+x4csbMHeDvxp+z+EolRPVF06GQrIDnLggeEW9JMA1A8vfIPZSyL96y1dzg/PhKsZzIDxgzWQ//cPzf4u1vlAhJiaZTP8cjxrAlg9fyNnRujT+KNJdTGLYDwVsicaA/fhzUYe3xJJSsdjbTTmUZYy9SZFe+P8ODxrHLMU1veDMo2sSIci5H119Otue1MeByXFE6YerJa0G2881D3Gi7HWaDM9oCOuWPuXHmnFQwITfLgfNWJ8CvQFCfXX36UmdTghfmHNH0bI/Zh+Q2ibD87hLTP56QDwmtP7pXu8JuMvtDs/4ByUonuEiLeRPrnxK9CintK9fCTK0L4AF78bmx4qww9TeUM2rxeXmzCynxdafhulP4DLw7Idk6fS21H824ocJwUMOhRuPbcDZoGU5clJaaWDXl0GCg7oKeuOhXNxgeVD34nEpi+j42T+sGaGMNPRmXGz5llSY/r0mAetSc1Eek7VDvsLs2UNp5IaXa1nMeyc2+deVDNttyIIfQFOrfMVNRe1oulyTp316l0Tw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
