apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAyBjs2WBC4LAoPWXxkAcG0ggE+bbKdUfdOqngvUJFCfG1MhNzq/g8cdxeZTuSM0EDZ5bRR73ItsQXUOg6HVj7qDaw4JqdycVsggBnMABM/xjFl6njMO5tILk5aAM9K+Se4OjBU/Yq+HlmxBDzr8OWPfyjkZfzRg4rDlQoAOTLtKODPBJQXwNlV/hmQYaJezuxZzYJDEXTmVaSax4hLPQaV7BqdLflmFEEs/ceRunOxh2MPxMpNuZlf7J1c4dc3GhafwifrQFbw1F7VKEolLYrnSZdwGc24FiJu86JjQyIrb7WKbIK/gY96/LaGOb/atuEEuB6Cf1+uc1821k6jsZ0PFJ35E82eWAfbMSoQiSx+WEMu0VApxYJd6PAT19LdbEI6Nb1J9qqd2xN93QHD18XkaTuCr8lrdo9X633EpYGjHRHSlSWDn8QoVi/AWEOG1WQtV3CDvYBnGuJYoh/hFL4HyrAyUk31oryalQBh69yqBqWWwTNYn9j6RLhJQlwjQoiS8Uxd3h1CzQD2PZvtzVK4jqacBS0DuR1XvyFMQb3e/YdpQFtuCY4IBmkCdVPO1pWmUFrsHvsxf52Bmz1AjrUKEyc4ID+tbU5cp4KS2H5alIvHPcMPBpO8EC0OFANZEgtkKS/Z69B4po3/fN8trm+8kZs/+l6C6gde40iE+C3ivc+XUFyJrbSabFV3AtepPmNRGjrvQdlW89V81+4zp2cjuR6/yDuZVgIoM4HCLyR3t4SIq3WhqpWs0IoBHFEaQc41SOKkHiC8SOXmflZjs6MkEbl4vhwN2PqVOA6nJZKSUcg1FdgCjLZKnvGpdEUQrLAKcIdVNixuuziYFIzveFm82Fer6WbVrP9BlMN71E0DRM3PWj0ftTKQdK1D1tKNQeeFV33jKY/IEuc7qHLcAOfplg==
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared
