---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgDhOVte2AfSDGEbDx4fX/H63wbC560gCNQdxi3sOT/0Wa1tCs5TVhCu1ldi5ByNQfez0VrqR2RL+dAB+MKuTR2ZHOsK/ExI1lvDRu6Jv3rbxkV9/ikezoiS99XpjdzWLcZLwJWlow6+iqkAz2CW8cg2zKWYB+ymj0TkDuihoD528XMOfByF0gBXoI5n0QhnJbCQKNgnADeZ7wLbaXnEfIPl006e/hfUIc/YiC21q42w8goFnyjCnEHYR3ZSOk0PxhmtqkiLNt1wZLtXxV7zVcEN3/3LQps+fwL3vCEPzWL58zxcjJBNk+CIYb7I1ZfHuBWrkyennjDlfBmtm2VVH5jSt/NmVf0/zMpJpmvE7mMF9vBi+m1ZulaBhPYTIyKhfSOToBwlg0wpJU6umu1MxxtYD9ScQiKWfpd0v7Hyyf98lFTXV+KjPpyYhJBN19aQ/VMWJs0uksYqf/qkSmpoByOsFsTZ65DD9TWKAbi7pUzOiJ23MpvBqor/DKMJfmSz/fH3VLqNdYJzRqQhCbhj24G3or8ilKuSACRS+OLVLrWktioH+mt2cstgjFt6izzJHQ+A1Oc5n3RQHpBA43GIPDUV7Xefft02aZEdnBpyOnmwPT3nDMoXYSFLc87/mxxTULBv98np3t1141gqGOfxB2P2ABiyVvzCAY+oBZoyZNswKLnDNbY28EGGq7VYcSA8pLeaQNVkxkcyBgsLYVF/vY+I8NKOMoJ06vtRIVHJ32GVhFgYVqARW3uZvvBfg+vNzHLAwNopk928h+qJfViPXNFKXFr4ecvGu6Dcyv7mtuIXsBRobll4dBQFuUrZipmuQ9kgIVaYelhlzeyuxk7zKiaqs6V3X0ERehCc98lmKS73zniWfrR9H5PY68IRDaIK0MXhcpvM7JZXBoMbc76jwhOWrQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
