apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAE0euKj9wIUJbdudgewH/xj5o9aDhRZBp797vtJsC76y9x73Ezp9Amn6fyQQON88jxsz5MfWDKCPBfTnxC89wX+7Lme2/6E/3W1qF0cdND81BzyBx4JLL2BznDJZXv+O3zcjeV3Y8twMBvXJ8pDELvLepUyLuncogDclIbaJHnaK6OYpkTgPdnJQTl4X0PfQDOSwvZoP0JulA3pPKoFZXleOoqFY3FcX/O6PJ87HU5ek1QGuVGMq3JkT+qrfmTSegjd/ZzIkuL0GcxN7GdpfjNaQ/PYBz0wDO/WXyItl+VtqJamAHpDegb+VaHyABLpk3XtGx+3bF3F51ghJeGA0LQqGE1S7bqouTvJVoKRcNSMqcPmRdXkJGZ+R0wSI/IT7HGmdHxpXisrz7n8r1v/Pg20af/WCpLQCA+rOaNQsyG2CkBLWdvWIOSVVBas0YFb5hKsx8XD9F8bcWBK42IrebIaIIgP6981B8fyLsn+BYvw3H/AQkZP9C8F9H7zxqYyx9N5zOUSmKmHFmwDHwCVjeZrRI90A+mKIdEmiMNIAvxAwjpMLdMRvILrD0bAF1hn8CVhnEBgf9ILfuLMRIJr7m8vW9pUPH+KMx8dGiy5NFMKWjXipd+y8prhIclMgeY7WCcGKFE9Znj93MkuMUbL+s+IwIaFiOujsbXTIYctrSaEULh40wPCN5B2ZFQ9/tYBupbXWS7lLu7xJYrOJMiXsc6pDgME6puu4moE+Lmym6juwYlHSDfJNX10V1YMN92kotljU6ZcWB2rk6u8P+H7N3Xbt3Vzi3qhbCht6wimUDAJVpkG6Av0G5e2ufHL3YOowh3InejNGwTOPAyLpIgniMPt33Ky5jFbvt0eCQvsaUrVQDWJDAvO5L65AFyyt/UNqb8E+ctED/x4kwk3eOOJek+1Q==
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared