apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
        - image: adguard/adguardhome:v0.107.48
          imagePullPolicy: IfNotPresent
          name: adguard
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dchp
              containerPort: 67
              protocol: UDP
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/adguardhome/conf
              name: adguard-conf
            - mountPath: /opt/adguardhome/work
              name: adguard-work
      volumes:
        - name: adguard-conf
          persistentVolumeClaim:
            claimName: adguard-conf
        - name: adguard-work
          persistentVolumeClaim:
            claimName: adguard-work
