apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-conf
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.42
    path: /rpool/data/adguard-conf