apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: adguard-conf
  resources:
    requests:
      storage: 1Gi